---
# Service
apiVersion: v1
kind: Service
metadata:
  name: demo-tiny-one
  labels:
    component: tiny
spec:
  selector:
    app: demo-tiny-one
  ports:
    - port: 80
      targetPort: 8080
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-tiny-one
  labels:
    component: tiny
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-tiny-one
  template:
    metadata:
      labels:
        app: demo-tiny-one
    spec:
      containers:
        - name: demo-tiny-one
          image: philippecharriere494/tiny-service:0.0.3
          env:
          - name: MESSAGE
            value: "üëã Hello World üåç"
          ports:
            - containerPort: 8080
          #imagePullPolicy: Always
          imagePullPolicy: IfNotPresent

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-tiny-one
  labels:
    component: tiny
spec:
  rules:
    - host: demo-tiny-one.3f1e2ff0-d14f-46a0-9601-c78cd127f940.k8s.civo.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: demo-tiny-one
              port: 
                number: 80
